
CREATE TABLE INDX_OBJIDO(
	`Id`							INT(11) NOT NULL AUTO_INCREMENT
	,`Offset`						VARCHAR(18) NULL DEFAULT NULL
	,`Vcn`							BIGINT NULL DEFAULT NULL
	,`IsNotLeaf`					TINYINT(1) NULL DEFAULT NULL
	,`LastLsn`						BIGINT NULL DEFAULT NULL
	,`FromIndxSlack`				TINYINT(1) NULL DEFAULT NULL
	,`DataOffset`					SMALLINT(5) NULL DEFAULT NULL
	,`DataSize`						SMALLINT(5) NULL DEFAULT NULL
	,`Padding1`						INT(11) NULL DEFAULT NULL
	,`IndexEntrySize`				SMALLINT(5) NULL DEFAULT NULL
	,`IndexKeySize`					SMALLINT(5) NULL DEFAULT NULL
	,`Flags`						VARCHAR(6) NULL DEFAULT NULL
	,`Padding2`						SMALLINT(5) NULL DEFAULT NULL
	,`MftRef`						BIGINT  NOT NULL
	,`MftRefSeqNo`					SMALLINT(5)  NOT NULL
	,`ObjectId`						VARCHAR(38) NOT NULL
	,`ObjectId_Version`				TINYINT(2) NULL DEFAULT NULL
	,`ObjectId_Timestamp`			DATETIME(6)  NULL DEFAULT NULL
	,`ObjectId_TimestampDec`		BIGINT  NULL DEFAULT NULL
	,`ObjectId_ClockSeq`			SMALLINT(5) NULL DEFAULT NULL
	,`ObjectId_Node`				VARCHAR(17) NULL DEFAULT NULL
	,`BirthVolumeId`				VARCHAR(38) NOT NULL
	,`BirthVolumeId_Version`		TINYINT(2) NULL DEFAULT NULL
	,`BirthVolumeId_Timestamp`		DATETIME(6)  NULL DEFAULT NULL
	,`BirthVolumeId_TimestampDec`	BIGINT  NULL DEFAULT NULL
	,`BirthVolumeId_ClockSeq`		SMALLINT(5) NULL DEFAULT NULL
	,`BirthVolumeId_Node`			VARCHAR(17) NULL DEFAULT NULL
	,`BirthObjectId`				VARCHAR(38) NOT NULL
	,`BirthObjectId_Version`		TINYINT(2) NULL DEFAULT NULL
	,`BirthObjectId_Timestamp`		DATETIME(6)  NULL DEFAULT NULL
	,`BirthObjectId_TimestampDec`	BIGINT  NULL DEFAULT NULL
	,`BirthObjectId_ClockSeq`		SMALLINT(5) NULL DEFAULT NULL
	,`BirthObjectId_Node`			VARCHAR(17) NULL DEFAULT NULL
	,`DomainId`						VARCHAR(38) NOT NULL
	,`DomainId_Version`				TINYINT(2) NULL DEFAULT NULL
	,`DomainId_Timestamp`			DATETIME(6)  NULL DEFAULT NULL
	,`DomainId_TimestampDec`		BIGINT  NULL DEFAULT NULL
	,`DomainId_ClockSeq`			SMALLINT(5) NULL DEFAULT NULL
	,`DomainId_Node`				VARCHAR(17) NULL DEFAULT NULL
	,`TextInformation`				VARCHAR(256) NULL DEFAULT NULL
	,PRIMARY KEY (Id)
);